spring:
  application:
    name : auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/mystoredb1?createDatabaseIfNotExist=true
    username: root
    password: Root@123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect

    show-sql: true
server:
  port: 9093